### ISSUE TITLE
Error when using -p

### ISSUE THREAD

**Issue by elskewe** [Kraymer/replica#1]
After running (with `-u`) Replica on two directories with 10 files each in it, it got the error message `Error: SRC and DEST must have same number of files`.  So I tried using `-u -p`, but then I got the following:
```
Traceback (most recent call last):
  File "/usr/local/bin/replica", line 11, in <module>
    load_entry_point('replica==0.1.1', 'console_scripts', 'replica')()
  File "build/bdist.linux-x86_64/egg/replica/cli.py", line 123, in main
  File "build/bdist.linux-x86_64/egg/replica/cli.py", line 71, in expand_args
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by Kraymer** [comment]
Can you execute a `ls` in each directory and post here the results ? thks

**Comment by elskewe** [comment]
SRC:
```
01 I Can Take It from There.mp3  06 Old Love Feels New.mp3
02 Lost.mp3                      07 You.mp3
03 Tomorrow.mp3                  08 Flashlight.mp3
04 Save Water, Drink Beer.mp3    09 When She's On.mp3
05 Neon.mp3                      10 She's Got This Thing About Her.mp3
```

DEST:
```
01 I Can Take It from There.m4a  06 Old Love Feels New.m4a
02 Lost.m4a                      07 You.m4a
03 Tomorrow.m4a                  08 Flashlight.m4a
04 Save Water, Drink Beer.m4a    09 When She's On.m4a
05 Neon.m4a                      10 She's Got This Thing About Her.m4a
```

**Comment by Kraymer** [comment]
Both src and target files need to be in mp3 format.

**Comment by elskewe** [comment]
Oh, I was somehow thinking it would work with the most audio codecs. The readme explicitly mentions mp3, so I have no idea why I thought that. Thanks for clearing that up!
